### ISSUE TITLE
Articles not loading on initial launch 

### ISSUE THREAD

**Issue by git-Pqrd** [justdjango/DjReact#1]
When freshly installed the app won't fetch the articles because 
componentWillReceiveProps(newProps) { if (newProps) } // components/ArticleListView

return null so it won't fetch the articles. 

I simply added 
componentWillMount() {}
and pasted the {  axios.get('.....') } part. 

Hopes it help if anyone is stuck

**Comment by mattfreire** [comment]
@git-Pqrd Thanks for this. Will add it in
