### ISSUE TITLE
CORS issues?

### ISSUE THREAD

**Issue by leslie-alldridge** [justdjango/DjReact#2]
Hi there, when running master branch I'm unable to sign up, add posts or login due to CORS issues.

**Comment by Butonix** [comment]
> Hi there, when running master branch I'm unable to sign up, add posts or login due to CORS issues.

install this package according to the instructions
https://github.com/ottoyiu/django-cors-headers

**Comment by justdjango** [comment]
This package is already defined in the requirements of this project. Closing this issue.
