### ISSUE TITLE
sign up is failing with error Unauthorized: /rest-auth/registration/

### ISSUE THREAD

**Issue by kimrop19** [justdjango/DjReact#3]
I dont know what the issue is but login is working fine, however signup ids failing with error Unauthorized: /rest-auth/registration/ in django

**Comment by ThomasNucleus** [comment]
I get the same issue. 

It returns a 403 error:
{"detail":"CSRF Failed: CSRF token missing or incorrect."}

How do we handle this?

**Comment by ThomasNucleus** [comment]
If this line is removed in the settings file it works:
'rest_framework.authentication.BasicAuthentication',
https://github.com/justdjango/DjReact/blob/f0ff7bc0730d6e772ee1c0189c29676e0387b2d5/djreact/settings.py#L97

I looked at the demo project of django-rest-auth and they don't use BasicAuthentication
https://github.com/Tivix/django-rest-auth/blob/master/demo/demo/settings.py

So is removing this line the way to go?

**Comment by mattfreire** [comment]
@ThomasNucleus @kimrop19 sorry about this

Django was looking for a CSRF token in the request because SessionAuthentication was specified. I've cleaned up the settings [in a new commit](https://github.com/justdjango/DjReact/commit/cb9dc6ee5202c14a0e1861d2a0bff2ad8740d64e)
